name: Demo

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      demo-output: ${{ steps.set-output-step.outputs.demo-output }}
    steps:
      - name: Set output value
        id: set-output-step
        run: echo "::set-output name=demo-output::Hello from Demo Job"
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Use output from test job
        run: echo "The output from test job is ${{ needs.test.outputs.demo-output }}"
