name: ISSUES

on:
  issues:
    types:
      [
        opened,
        edited,
        closed,
        reopened,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        milestoned,
        demilestoned,
        transferred,
        pinned,
        unpinned,
      ]

jobs:
  log-issue-event:
    runs-on: ubuntu-latest
    steps:
      - name: Log issue event
        run: echo "Issue event of type '${{ github.event.action }}' received for issue #${{ github.event.issue.number }} titled '${{ github.event.issue.title }}'."
